server:
  port: 9002
spring:
  application:
    name: myday-consumer-feign
  zipkin:
    base-url: http://localhost:7004
  sleuth:
    sampler:
      percentage: 1.0
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
